FROM amd64/python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt ./
RUN apt-get update && apt-get install -y git
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./data_sync_module.py" ]