version: "3.9"

networks:
  broker-net:
    driver: bridge

services:
  broker:
    build: ./broker
    ports:
      - "1883:1883"
    networks:
      - broker-net

  publisher:
    build: ./publisher
    environment:
      - HOST=broker
    networks:
      - broker-net
    depends_on:
      - broker

  subscriber:
    build: ./subscriber
    environment:
      - HOST=broker
    networks:
      - broker-net
    depends_on:
      - broker
